fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: [--fix, --fix-errors]
      - id: cppcheck
        args: [--std=c++20]