fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
      - id: uncrustify
        args: [--replace, --no-backup]
      - id: cppcheck